/**
 * Lexido components
 * A centralized collection of components.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ExpenditureSplit } from './expenditureSplit';
import { OpeningBalance } from './openingBalance';
import { Refund } from './refund';

export class BookkeepingInner {
    'timestamp': Date;
    'amount': number;
    'expenditureRef': string;
    'command': string;
    'kind'?: BookkeepingInner.KindEnum = BookkeepingInner.KindEnum.Opening;

    static discriminator: string | undefined = "kind";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "Date"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number"
        },
        {
            "name": "expenditureRef",
            "baseName": "expenditureRef",
            "type": "string"
        },
        {
            "name": "command",
            "baseName": "command",
            "type": "string"
        },
        {
            "name": "kind",
            "baseName": "kind",
            "type": "BookkeepingInner.KindEnum"
        }    ];

    static getAttributeTypeMap() {
        return BookkeepingInner.attributeTypeMap;
    }
}

export namespace BookkeepingInner {
    export enum KindEnum {
        Opening = <any> 'opening'
    }
}
