/**
 * Lexido components
 * A centralized collection of components.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Requisition } from './requisition';

export class Expenditure {
    'timestamp': Date;
    'amount': number;
    'requisition': Requisition;
    'splits'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "Date"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number"
        },
        {
            "name": "requisition",
            "baseName": "requisition",
            "type": "Requisition"
        },
        {
            "name": "splits",
            "baseName": "splits",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return Expenditure.attributeTypeMap;
    }
}

