/**
 * Lexido components
 * A centralized collection of components.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class FillInTheBlank {
    'content': { [key: string]: string; };
    'score': number;
    'difficultness': number;
    'reference': string;
    'kind'?: FillInTheBlank.KindEnum = FillInTheBlank.KindEnum.FillInTheBlankV1;
    'correctAnswer': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "content",
            "baseName": "content",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "score",
            "baseName": "score",
            "type": "number"
        },
        {
            "name": "difficultness",
            "baseName": "difficultness",
            "type": "number"
        },
        {
            "name": "reference",
            "baseName": "reference",
            "type": "string"
        },
        {
            "name": "kind",
            "baseName": "kind",
            "type": "FillInTheBlank.KindEnum"
        },
        {
            "name": "correctAnswer",
            "baseName": "correct_answer",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return FillInTheBlank.attributeTypeMap;
    }
}

export namespace FillInTheBlank {
    export enum KindEnum {
        FillInTheBlankV1 = <any> 'FillInTheBlankV1'
    }
}
