/**
 * Lexido components
 * A centralized collection of components.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Option } from './option';

export class MCQuestion {
    'content': { [key: string]: string; };
    'score': number;
    'difficultness': number;
    'reference': string;
    'kind'?: MCQuestion.KindEnum = MCQuestion.KindEnum.McQuestionV1;
    'correctAnswer': Option;
    'wrongOptions': Array<Option>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "content",
            "baseName": "content",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "score",
            "baseName": "score",
            "type": "number"
        },
        {
            "name": "difficultness",
            "baseName": "difficultness",
            "type": "number"
        },
        {
            "name": "reference",
            "baseName": "reference",
            "type": "string"
        },
        {
            "name": "kind",
            "baseName": "kind",
            "type": "MCQuestion.KindEnum"
        },
        {
            "name": "correctAnswer",
            "baseName": "correct_answer",
            "type": "Option"
        },
        {
            "name": "wrongOptions",
            "baseName": "wrong_options",
            "type": "Array<Option>"
        }    ];

    static getAttributeTypeMap() {
        return MCQuestion.attributeTypeMap;
    }
}

export namespace MCQuestion {
    export enum KindEnum {
        McQuestionV1 = <any> 'MCQuestionV1'
    }
}
