/**
 * Lexido components
 * A centralized collection of components.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class OpeningBalance {
    'timestamp': Date;
    'amount': number;
    'kind'?: OpeningBalance.KindEnum = OpeningBalance.KindEnum.Opening;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "Date"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number"
        },
        {
            "name": "kind",
            "baseName": "kind",
            "type": "OpeningBalance.KindEnum"
        }    ];

    static getAttributeTypeMap() {
        return OpeningBalance.attributeTypeMap;
    }
}

export namespace OpeningBalance {
    export enum KindEnum {
        Opening = <any> 'opening'
    }
}
