/**
 * Lexido components
 * A centralized collection of components.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BookkeepingInner } from './bookkeepingInner';
import { PointReason } from './pointReason';

export class Point {
    'kind': Point.KindEnum;
    'points': number;
    'expiration': Date;
    'reason': PointReason;
    'bookkeeping': Array<BookkeepingInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "kind",
            "baseName": "kind",
            "type": "Point.KindEnum"
        },
        {
            "name": "points",
            "baseName": "points",
            "type": "number"
        },
        {
            "name": "expiration",
            "baseName": "expiration",
            "type": "Date"
        },
        {
            "name": "reason",
            "baseName": "reason",
            "type": "PointReason"
        },
        {
            "name": "bookkeeping",
            "baseName": "bookkeeping",
            "type": "Array<BookkeepingInner>"
        }    ];

    static getAttributeTypeMap() {
        return Point.attributeTypeMap;
    }
}

export namespace Point {
    export enum KindEnum {
        Points = <any> 'points'
    }
}
