/**
 * Lexido components
 * A centralized collection of components.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FillInTheBlank } from './fillInTheBlank';
import { MCQuestion } from './mCQuestion';
import { Option } from './option';
import { TrueFalseNotGivenEnum } from './trueFalseNotGivenEnum';
import { TrueFalseNotGivenQuestion } from './trueFalseNotGivenQuestion';

export class QuestionsInner {
    'content': { [key: string]: string; };
    'score': number;
    'difficultness': number;
    'reference': string;
    'kind'?: QuestionsInner.KindEnum = QuestionsInner.KindEnum.TrueFalseNotGivenQuestionV1;
    'correctAnswer': TrueFalseNotGivenEnum;
    'wrongOptions': Array<Option>;

    static discriminator: string | undefined = "kind";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "content",
            "baseName": "content",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "score",
            "baseName": "score",
            "type": "number"
        },
        {
            "name": "difficultness",
            "baseName": "difficultness",
            "type": "number"
        },
        {
            "name": "reference",
            "baseName": "reference",
            "type": "string"
        },
        {
            "name": "kind",
            "baseName": "kind",
            "type": "QuestionsInner.KindEnum"
        },
        {
            "name": "correctAnswer",
            "baseName": "correct_answer",
            "type": "TrueFalseNotGivenEnum"
        },
        {
            "name": "wrongOptions",
            "baseName": "wrong_options",
            "type": "Array<Option>"
        }    ];

    static getAttributeTypeMap() {
        return QuestionsInner.attributeTypeMap;
    }
}

export namespace QuestionsInner {
    export enum KindEnum {
        TrueFalseNotGivenQuestionV1 = <any> 'TrueFalseNotGivenQuestionV1'
    }
}
