/**
 * Lexido components
 * A centralized collection of components.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Refund {
    'timestamp': Date;
    'amount': number;
    'expenditureRef': string;
    'command': string;
    'kind'?: Refund.KindEnum = Refund.KindEnum.Refund;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "Date"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number"
        },
        {
            "name": "expenditureRef",
            "baseName": "expenditureRef",
            "type": "string"
        },
        {
            "name": "command",
            "baseName": "command",
            "type": "string"
        },
        {
            "name": "kind",
            "baseName": "kind",
            "type": "Refund.KindEnum"
        }    ];

    static getAttributeTypeMap() {
        return Refund.attributeTypeMap;
    }
}

export namespace Refund {
    export enum KindEnum {
        Refund = <any> 'refund'
    }
}
