/**
 * Lexido components
 * A centralized collection of components.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { RequisitionStatus } from './requisitionStatus';

export class Requisition {
    'args': { [key: string]: any; };
    'status': RequisitionStatus;
    'retry'?: number = 0;
    'resourceRef': string | null;
    'command': string;
    'customFields': { [key: string]: string; } | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "args",
            "baseName": "args",
            "type": "{ [key: string]: any; }"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "RequisitionStatus"
        },
        {
            "name": "retry",
            "baseName": "retry",
            "type": "number"
        },
        {
            "name": "resourceRef",
            "baseName": "resourceRef",
            "type": "string"
        },
        {
            "name": "command",
            "baseName": "command",
            "type": "string"
        },
        {
            "name": "customFields",
            "baseName": "customFields",
            "type": "{ [key: string]: string; }"
        }    ];

    static getAttributeTypeMap() {
        return Requisition.attributeTypeMap;
    }
}

export namespace Requisition {
}
