/**
 * Lexido components
 * A centralized collection of components.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export enum RequisitionStatus {
    Pending = <any> 'pending',
    Failed = <any> 'failed',
    Rejected = <any> 'rejected',
    Canceled = <any> 'canceled',
    Success = <any> 'success'
}
