/**
 * Lexido components
 * A centralized collection of components.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Usability {
    'tag': Array<string>;
    'suitability': boolean;
    'reason': string;
    'difficultness': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "tag",
            "baseName": "tag",
            "type": "Array<string>"
        },
        {
            "name": "suitability",
            "baseName": "suitability",
            "type": "boolean"
        },
        {
            "name": "reason",
            "baseName": "reason",
            "type": "string"
        },
        {
            "name": "difficultness",
            "baseName": "difficultness",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Usability.attributeTypeMap;
    }
}

