/**
 * Lexido components
 * A centralized collection of components.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ExerciseContent } from './exerciseContent';
import { QuestionsInner } from './questionsInner';
import { Usability } from './usability';

export class VideoListeningExercise {
    'meta': { [key: string]: any; };
    'content': ExerciseContent;
    'kind'?: VideoListeningExercise.KindEnum = VideoListeningExercise.KindEnum.VideoListeningExerciseV1;
    'title': string;
    'usability': Usability;
    'keyVocabolary': Array<{ [key: string]: string; }>;
    'description': { [key: string]: string; };
    'questions': Array<QuestionsInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "meta",
            "baseName": "meta",
            "type": "{ [key: string]: any; }"
        },
        {
            "name": "content",
            "baseName": "content",
            "type": "ExerciseContent"
        },
        {
            "name": "kind",
            "baseName": "kind",
            "type": "VideoListeningExercise.KindEnum"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "usability",
            "baseName": "usability",
            "type": "Usability"
        },
        {
            "name": "keyVocabolary",
            "baseName": "keyVocabolary",
            "type": "Array<{ [key: string]: string; }>"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "questions",
            "baseName": "questions",
            "type": "Array<QuestionsInner>"
        }    ];

    static getAttributeTypeMap() {
        return VideoListeningExercise.attributeTypeMap;
    }
}

export namespace VideoListeningExercise {
    export enum KindEnum {
        VideoListeningExerciseV1 = <any> 'VideoListeningExerciseV1'
    }
}
