/**
 * Lexido components
 * A centralized collection of components.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ExpenditureSplit } from '../models/ExpenditureSplit';
import { OpeningBalance } from '../models/OpeningBalance';
import { Refund } from '../models/Refund';
import { HttpFile } from '../http/http';

/**
 * @type BookkeepingInner
 * Type
 * @export
 */
export type BookkeepingInner = ExpenditureSplit | OpeningBalance | Refund;

/**
* @type BookkeepingInnerClass
* @export
*/
export class BookkeepingInnerClass {
    static readonly discriminator: string | undefined = "kind";

    static readonly mapping: {[index: string]: string} | undefined = {
        "expenditure": "ExpenditureSplit",
        "opening": "OpeningBalance",
        "refund": "Refund",
    };
}


