/**
 * Lexido components
 * A centralized collection of components.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { QuestionsInner } from '../models/QuestionsInner';
import { Usability } from '../models/Usability';
import { HttpFile } from '../http/http';

export class Exercise {
    'meta': { [key: string]: any; };
    'kind': string;
    'title': string;
    'usability': Usability;
    'keyVocabolary': Array<any>;
    'description': any;
    'questions': Array<QuestionsInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "meta",
            "baseName": "meta",
            "type": "{ [key: string]: any; }",
            "format": ""
        },
        {
            "name": "kind",
            "baseName": "kind",
            "type": "string",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "usability",
            "baseName": "usability",
            "type": "Usability",
            "format": ""
        },
        {
            "name": "keyVocabolary",
            "baseName": "keyVocabolary",
            "type": "Array<any>",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "any",
            "format": ""
        },
        {
            "name": "questions",
            "baseName": "questions",
            "type": "Array<QuestionsInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Exercise.attributeTypeMap;
    }

    public constructor() {
    }
}
