/**
 * Lexido components
 * A centralized collection of components.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Requisition } from '../models/Requisition';
import { HttpFile } from '../http/http';

export class Expenditure {
    'timestamp': Date;
    'amount': number;
    'requisition': Requisition;
    'splits'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number",
            "format": ""
        },
        {
            "name": "requisition",
            "baseName": "requisition",
            "type": "Requisition",
            "format": ""
        },
        {
            "name": "splits",
            "baseName": "splits",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Expenditure.attributeTypeMap;
    }

    public constructor() {
    }
}
