/**
 * Lexido components
 * A centralized collection of components.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Option } from '../models/Option';
import { HttpFile } from '../http/http';

export class MCQuestion {
    'content': any;
    'score': number;
    'difficultness': number;
    'reference': string;
    'kind'?: MCQuestionKindEnum;
    'correctAnswer': Option;
    'wrongOptions': Array<Option>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "content",
            "baseName": "content",
            "type": "any",
            "format": ""
        },
        {
            "name": "score",
            "baseName": "score",
            "type": "number",
            "format": ""
        },
        {
            "name": "difficultness",
            "baseName": "difficultness",
            "type": "number",
            "format": ""
        },
        {
            "name": "reference",
            "baseName": "reference",
            "type": "string",
            "format": ""
        },
        {
            "name": "kind",
            "baseName": "kind",
            "type": "MCQuestionKindEnum",
            "format": ""
        },
        {
            "name": "correctAnswer",
            "baseName": "correct_answer",
            "type": "Option",
            "format": ""
        },
        {
            "name": "wrongOptions",
            "baseName": "wrong_options",
            "type": "Array<Option>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MCQuestion.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum MCQuestionKindEnum {
    McQuestionV1 = 'MCQuestionV1'
}

