/**
 * Lexido components
 * A centralized collection of components.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class Option {
    'content': string;
    'explanation': any;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "content",
            "baseName": "content",
            "type": "string",
            "format": ""
        },
        {
            "name": "explanation",
            "baseName": "explanation",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Option.attributeTypeMap;
    }

    public constructor() {
    }
}
