/**
 * Lexido components
 * A centralized collection of components.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BookkeepingInner } from '../models/BookkeepingInner';
import { PointReason } from '../models/PointReason';
import { HttpFile } from '../http/http';

export class Point {
    'kind': PointKindEnum;
    'points': number;
    'expiration': Date;
    'reason': PointReason;
    'bookkeeping': Array<BookkeepingInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "kind",
            "baseName": "kind",
            "type": "PointKindEnum",
            "format": ""
        },
        {
            "name": "points",
            "baseName": "points",
            "type": "number",
            "format": ""
        },
        {
            "name": "expiration",
            "baseName": "expiration",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "reason",
            "baseName": "reason",
            "type": "PointReason",
            "format": ""
        },
        {
            "name": "bookkeeping",
            "baseName": "bookkeeping",
            "type": "Array<BookkeepingInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Point.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum PointKindEnum {
    Points = 'points'
}

