/**
 * Lexido components
 * A centralized collection of components.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FillInTheBlank } from '../models/FillInTheBlank';
import { MCQuestion } from '../models/MCQuestion';
import { TrueFalseNotGivenQuestion } from '../models/TrueFalseNotGivenQuestion';
import { HttpFile } from '../http/http';

/**
 * @type QuestionsInner
 * Type
 * @export
 */
export type QuestionsInner = FillInTheBlank | MCQuestion | TrueFalseNotGivenQuestion;

/**
* @type QuestionsInnerClass
* @export
*/
export class QuestionsInnerClass {
    static readonly discriminator: string | undefined = "kind";

    static readonly mapping: {[index: string]: string} | undefined = {
        "FillInTheBlankV1": "FillInTheBlank",
        "MCQuestionV1": "MCQuestion",
        "TrueFalseNotGivenQuestionV1": "TrueFalseNotGivenQuestion",
    };
}


