/**
 * Lexido components
 * A centralized collection of components.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequisitionStatus } from '../models/RequisitionStatus';
import { HttpFile } from '../http/http';

export class Requisition {
    'args': { [key: string]: any; };
    'status': RequisitionStatus;
    'retry'?: number;
    'resourceRef': string | null;
    'command': string;
    'customFields': { [key: string]: string; } | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "args",
            "baseName": "args",
            "type": "{ [key: string]: any; }",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "RequisitionStatus",
            "format": ""
        },
        {
            "name": "retry",
            "baseName": "retry",
            "type": "number",
            "format": ""
        },
        {
            "name": "resourceRef",
            "baseName": "resourceRef",
            "type": "string",
            "format": ""
        },
        {
            "name": "command",
            "baseName": "command",
            "type": "string",
            "format": ""
        },
        {
            "name": "customFields",
            "baseName": "customFields",
            "type": "{ [key: string]: string; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Requisition.attributeTypeMap;
    }

    public constructor() {
    }
}


