/**
 * Lexido components
 * A centralized collection of components.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TrueFalseNotGivenEnum } from '../models/TrueFalseNotGivenEnum';
import { HttpFile } from '../http/http';

export class TrueFalseNotGivenQuestion {
    'content': any;
    'score': number;
    'difficultness': number;
    'reference': string;
    'kind'?: TrueFalseNotGivenQuestionKindEnum;
    'correctAnswer': TrueFalseNotGivenEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "content",
            "baseName": "content",
            "type": "any",
            "format": ""
        },
        {
            "name": "score",
            "baseName": "score",
            "type": "number",
            "format": ""
        },
        {
            "name": "difficultness",
            "baseName": "difficultness",
            "type": "number",
            "format": ""
        },
        {
            "name": "reference",
            "baseName": "reference",
            "type": "string",
            "format": ""
        },
        {
            "name": "kind",
            "baseName": "kind",
            "type": "TrueFalseNotGivenQuestionKindEnum",
            "format": ""
        },
        {
            "name": "correctAnswer",
            "baseName": "correct_answer",
            "type": "TrueFalseNotGivenEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TrueFalseNotGivenQuestion.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum TrueFalseNotGivenQuestionKindEnum {
    TrueFalseNotGivenQuestionV1 = 'TrueFalseNotGivenQuestionV1'
}

