/**
 * Lexido components
 * A centralized collection of components.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class Usability {
    'tag': Array<string>;
    'suitability': boolean;
    'reason': string;
    'difficultness': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tag",
            "baseName": "tag",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "suitability",
            "baseName": "suitability",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "reason",
            "baseName": "reason",
            "type": "string",
            "format": ""
        },
        {
            "name": "difficultness",
            "baseName": "difficultness",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Usability.attributeTypeMap;
    }

    public constructor() {
    }
}
